sudo: required

language: generic

env:
  - BUILD_SYSTEM=npm
 # Temporarily disabled because of
 #   https://travis-ci.org/aantron/repromise/jobs/402821061#L482
 #  - BUILD_SYSTEM=esy
  - BUILD_SYSTEM=opam

script:
  bash test/travis.sh

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
