language: generic

jobs:
  include:
    - env: BUILD_SYSTEM=esy
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ./node_modules ~/.esy'
      install:
        - '[ ! -f ./node_modules/.bin/esy ] || ESY_CACHED=yes'
        - '[ "$ESY_CACHED" == yes ] || npm install --no-save esy'
        - '[ "$ESY_CACHED" != yes ] || SKIP_UPDATE=--skip-repository-update'
        - export PATH="$(pwd)/node_modules/.bin:$PATH"
        - esy install $SKIP_UPDATE
      script:
        - esy dune build test/test_main.exe
        - esy dune exec test/test_main.exe
      before_cache:
        - npm cache clean --force
        - rm -rf node_modules/.cache/_esy

    - env: BUILD_SYSTEM=npm
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ./node_modules'
      install:
        - '[ -d node_modules ] || npm install'
      script:
        - npm run test
        - bash test/bundle/size.sh
      before_cache:
        - ./node_modules/.bin/bsb -clean-world
        - npm cache clean --force

    - env: BUILD_SYSTEM=opam
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ~/.opam'
      install:
        - VERSION=2.0.5
        - OPAM=opam-$VERSION-x86_64-linux
        - wget https://github.com/ocaml/opam/releases/download/$VERSION/$OPAM
        - sudo mv $OPAM /usr/local/bin/opam
        - sudo chmod a+x /usr/local/bin/opam
        - opam init -ya --compiler=4.08.1 --disable-sandboxing
        - eval `opam env`
        - ocaml -version
        - opam install -y --deps-only .
      script:
        - BISECT_ENABLE=yes dune exec test/test_main.exe
        - bisect-ppx-report send-to Coveralls
        - opam lint
      before_cache:
        - opam clean

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.esy
    - $HOME/.opam
    - node_modules

notifications:
  email:
    on_success: always
    on_failure: always
