language: generic

jobs:
  include:
    - env: BUILD_SYSTEM=esy
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ./node_modules ~/.esy'
      install:
        - '[ ! -f ./node_modules/.bin/esy ] || ESY_CACHED=yes'
        - '[ "$ESY_CACHED" == yes ] || npm install --no-save esy'
        - '[ "$ESY_CACHED" != yes ] || SKIP_UPDATE=--skip-repository-update'
        - export PATH="$(pwd)/node_modules/.bin:$PATH"
        - esy install $SKIP_UPDATE
      script:
        - esy dune build test/test_main.exe
        - esy dune exec test/test_main.exe
      before_cache:
        - npm cache clean --force
        - rm -rf node_modules/.cache/_esy

    - env: BUILD_SYSTEM=npm
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ./node_modules'
      install:
        - npm install
      script:
        - make bucklescript-coverage
      before_cache:
        - ./node_modules/.bin/bsb -clean-world
        - npm cache clean --force

    - env: BUILD_SYSTEM=opam
      before_install:
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ~/.opam'
      install:
        - VERSION=2.0.5
        - OPAM=opam-$VERSION-x86_64-linux
        - wget https://github.com/ocaml/opam/releases/download/$VERSION/$OPAM
        - sudo mv $OPAM /usr/local/bin/opam
        - sudo chmod a+x /usr/local/bin/opam
        - opam init -ya --compiler=4.08.1 --disable-sandboxing
        - eval `opam env`
        - ocaml -version
        - opam install -y --deps-only .
      script:
        - make native-coverage
        - bisect-ppx-report send-to Coveralls
        - opam lint
      before_cache:
        - opam clean

    - env: BUILD_SYSTEM=docusaurus
      before_install:
        - '[ "$TRAVIS_BRANCH" == master ] || exit 0'
        - '[ "$TRAVIS_PULL_REQUEST" == false ] || exit 0'
        - '[ "$TRAVIS_EVENT_TYPE" != cron ] || exit 0'
        - '[ "$TRAVIS_REPO_SLUG" == aantron/repromise ] || exit 0'
        - '( git diff --name-only HEAD~ | grep "^doc/" ) || exit 0'
      install:
        - cd doc/website
        - '[ -d node_modules ] || npm install'
      script:
        - npm run build'
        - echo $DEPLOY_KEY | base64 --decode > ~/.ssh/docusaurus
        - chmod 400 ~/.ssh/docusaurus
        - echo >> ~/.ssh/config
        - echo "Host github.com" >> ~/.ssh/config
        - echo "  IdentityFile ~/.ssh/docusaurus" >> ~/.ssh/config
        - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        - git clone git@github.com:aantron/repromise.git gh-pages
        - cd gh-pages
        - git config user.name "Anton Bachin"
        - git config user.email "antonbachin@yahoo.com"
        - git checkout gh-pages
        - rm -rf *
        - cp -r ../build/repromise/* .
        - git add -A
        - git commit --amend --no-edit --reset-author
        - git push --force-with-lease
      before_cache:
        - npm cache clean --force
        - rm -rf ../node_modules/.cache/@babel/register

matrix:
  fast_finish: true
  allow_failures:
    - env: BUILD_SYSTEM=docusaurus

cache:
  directories:
    - $HOME/.esy
    - $HOME/.opam
    - node_modules
    - doc/website/node_modules

notifications:
  email:
    on_success: always
    on_failure: always
